### ISSUE TITLE
新功能建议

### ISSUE THREAD

**Issue by wwwangUCD** [geezmolycos/lizard-pet#1]
非常有意思的应用，感谢分享。建议增加一个小功能：鼠标左键把桌宠拽起来，放到其他位置。

**Comment by geezmolycos** [comment]
想法很好，已经在待做列表里了

**Comment by geezmolycos** [comment]
新发布的 v1.2.0 版本已经增加了鼠标拖动功能，但是受框架原理限制，拖动的不是很顺滑，龙不愿意被动来动去
